language: elixir

elixir:
  - 1.9.0

otp_release:
  - 22.0

sudo: required

services:
  - docker

before_install:
  - docker pull eventstore/eventstore
  - docker run -d --rm -p 2113:2113 -p 1113:1113 -e EVENTSTORE_START_STANDARD_PROJECTIONS=True -e EVENTSTORE_RUN_PROJECTIONS=all eventstore/eventstore
